name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache depndencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci # 바로 위에서 정의한 캐시를 사용하여 의존성을 설치
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache depndencies
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci 
      - name: Build website
        run: npm run build 
      - name: Publish JS filename
        id: publish
        # run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
        run: find dist/assets/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
        # 빌드 후 생성된 파일은 runner가 종료되면 삭제됨
        # 따라서, 빌드 후 생성된 파일을 아티팩트로 업로드하여 다음 job에서 사용할 수 있도록 함
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "Script file ${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run: echo "Deploying..."
